spring.application.name=admin-app

# データベース接続設定 (ポートを 5433 に指定)
spring.datasource.url=jdbc:postgresql://localhost:5433/customer_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernateの設定
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
# アプリ起動時にテーブルをドロップして新規作成（自動採番付きでテーブルが生成されます）
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update